name: twnel_face_app
description: Twnel Face App

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get: ^4.3.8
  animate_do: ^2.0.0
  google_fonts: ^2.1.0
  photo_view: ^0.13.0
  logger: ^1.1.0
  google_ml_kit: ^0.7.2

  #CAMERA
  permission_handler: 8.1.6
  camera: ^0.9.3
  path_provider: ^2.0.5
  path: ^1.8.0
  image_picker: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
